//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.AdventureWorksOBP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proizvod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvod()
        {
            this.Stavka = new HashSet<Stavka>();
        }

        public int IDProizvod { get; set; }
        [Required(ErrorMessage = "naziv je obavezan")]
        public string Naziv { get; set; }
        [Required (ErrorMessage = "Broj proizvoda je obavezan")]
        [Display(Name = "Broj Proizvoda")]
        public string BrojProizvoda { get; set; }
        [Required(ErrorMessage = "Boja proizvoda je obavezna")]
        public string Boja { get; set; }
        [Required(ErrorMessage = "Minimalna kolicina proizvoda je obavezna")]
        [Display(Name = "Minimalna Kolicina Na Skladistu")]
        public short MinimalnaKolicinaNaSkladistu { get; set; }
        [Required(ErrorMessage = "Cijena bez PDV-a je obavezna")]
        [Display(Name = "Cijena Bez PDV-a")]
        public decimal CijenaBezPDV { get; set; }
        [Required(ErrorMessage = "Potkategorija je obavezna")]
        [Display(Name = "Potkategorija")]
        public Nullable<int> PotkategorijaID { get; set; }
    
        public virtual Potkategorija Potkategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka> Stavka { get; set; }
    }
}
